// Static mock data for the Wedding Guestbook app
// Types and a sample dataset to support UI development without a backend.

export type GuestCategory = "VVIP" | "VIP" | "Regular";
export type RSVPStatus = "Ya" | "Tidak" | "Belum";
export type AttendanceStatus = "Hadir" | "Belum";
export type SouvenirStatus = "Terima" | "Pending";

export interface Guest {
  id: string;
  name: string;
  category: GuestCategory;
  rsvp: RSVPStatus;
  attendance: AttendanceStatus;
  souvenir: SouvenirStatus;
  phone?: string;
  table?: string;
}

// ~30 mixed entries for pagination and UI testing
export const guests: Guest[] = [
  {
    id: "G-0001",
    name: "Budi Santoso",
    category: "VVIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 812-1111-1111",
    table: "A1",
  },
  {
    id: "G-0002",
    name: "Siti Aminah",
    category: "VIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Pending",
    phone: "+62 813-2222-2222",
    table: "B2",
  },
  {
    id: "G-0003",
    name: "Adi Pratama",
    category: "Regular",
    rsvp: "Belum",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 814-3333-3333",
    table: "C3",
  },
  {
    id: "G-0004",
    name: "Dewi Lestari",
    category: "VIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 815-4444-4444",
    table: "B1",
  },
  {
    id: "G-0005",
    name: "Rudi Hartono",
    category: "Regular",
    rsvp: "Tidak",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 816-5555-5555",
    table: "D4",
  },
  {
    id: "G-0006",
    name: "Nina Saraswati",
    category: "VVIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 817-6666-6666",
    table: "A2",
  },
  {
    id: "G-0007",
    name: "Yusuf Alami",
    category: "VIP",
    rsvp: "Belum",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 818-7777-7777",
    table: "B3",
  },
  {
    id: "G-0008",
    name: "Lina Kusuma",
    category: "Regular",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Pending",
    phone: "+62 819-8888-8888",
    table: "C1",
  },
  {
    id: "G-0009",
    name: "Fajar Nugroho",
    category: "VIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 811-9999-9999",
    table: "B4",
  },
  {
    id: "G-0010",
    name: "Maya Putri",
    category: "Regular",
    rsvp: "Belum",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0001",
    table: "D1",
  },
  {
    id: "G-0011",
    name: "Agus Widodo",
    category: "Regular",
    rsvp: "Ya",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0002",
    table: "D2",
  },
  {
    id: "G-0012",
    name: "Rika Ayu",
    category: "VIP",
    rsvp: "Tidak",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0003",
    table: "B5",
  },
  {
    id: "G-0013",
    name: "Eka Saputra",
    category: "VVIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 812-0000-0004",
    table: "A3",
  },
  {
    id: "G-0014",
    name: "Tina Marlina",
    category: "Regular",
    rsvp: "Belum",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0005",
    table: "C2",
  },
  {
    id: "G-0015",
    name: "Dimas Seto",
    category: "VIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 812-0000-0006",
    table: "B6",
  },
  {
    id: "G-0016",
    name: "Ayu Wulandari",
    category: "Regular",
    rsvp: "Tidak",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0007",
    table: "D3",
  },
  {
    id: "G-0017",
    name: "Bayu Hidayat",
    category: "VIP",
    rsvp: "Belum",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0008",
    table: "B7",
  },
  {
    id: "G-0018",
    name: "Citra Dewi",
    category: "VVIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 812-0000-0009",
    table: "A4",
  },
  {
    id: "G-0019",
    name: "Hendra Kurniawan",
    category: "Regular",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Pending",
    phone: "+62 812-0000-0010",
    table: "C4",
  },
  {
    id: "G-0020",
    name: "Indah Sari",
    category: "VIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 812-0000-0011",
    table: "B8",
  },
  {
    id: "G-0021",
    name: "Joko Susilo",
    category: "Regular",
    rsvp: "Belum",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0012",
    table: "D5",
  },
  {
    id: "G-0022",
    name: "Kartika Rahma",
    category: "VIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 812-0000-0013",
    table: "B9",
  },
  {
    id: "G-0023",
    name: "Leo Prabowo",
    category: "Regular",
    rsvp: "Tidak",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0014",
    table: "D6",
  },
  {
    id: "G-0024",
    name: "Mira Handayani",
    category: "VIP",
    rsvp: "Belum",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0015",
    table: "B10",
  },
  {
    id: "G-0025",
    name: "Nando Yudha",
    category: "Regular",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 812-0000-0016",
    table: "C5",
  },
  {
    id: "G-0026",
    name: "Oki Firmansyah",
    category: "VVIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 812-0000-0017",
    table: "A5",
  },
  {
    id: "G-0027",
    name: "Putri Melati",
    category: "Regular",
    rsvp: "Belum",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0018",
    table: "D7",
  },
  {
    id: "G-0028",
    name: "Qori Lailatul",
    category: "VIP",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Pending",
    phone: "+62 812-0000-0019",
    table: "B11",
  },
  {
    id: "G-0029",
    name: "Rama Aditya",
    category: "Regular",
    rsvp: "Ya",
    attendance: "Hadir",
    souvenir: "Terima",
    phone: "+62 812-0000-0020",
    table: "C6",
  },
  {
    id: "G-0030",
    name: "Salsa Nabila",
    category: "VIP",
    rsvp: "Tidak",
    attendance: "Belum",
    souvenir: "Pending",
    phone: "+62 812-0000-0021",
    table: "B12",
  },
];

export default guests;
